# Generated by Django 3.1.7 on 2022-02-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220210_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='num_of_orders',
            field=models.IntegerField(null=True),
        ),
    ]
