# Generated by Django 3.1.7 on 2022-02-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220210_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='num_of_orders',
        ),
    ]
