# Generated by Django 3.1.7 on 2022-02-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customer_num_of_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='num_of_orders',
            field=models.IntegerField(null=True),
        ),
    ]
